### ISSUE TITLE
Duplicate .desktop icon

### ISSUE THREAD

**Issue by Justinzobel** [evolve-os/journal#12]
I pulled and built this and it creates 2 entries in the menu..

**Comment by ryanleesipes** [comment]
Haven't had this issue. Hmm... Have you had it installed in the past?

**Comment by Justinzobel** [comment]
I have but I'm pretty sure it happened on the first install.

**Comment by ryanleesipes** [comment]
Oh, yes, you are correct. It's because I have it going under two
categories. I'll need to adjust that.

**Comment by ryanleesipes** [comment]
This should be fixed, removed the "Development" category from the .desktop file.
