### ISSUE TITLE
Add Undo Functionality

### ISSUE THREAD

**Issue by ryanleesipes** [evolve-os/journal#13]
Currently no Undo functionality in, will need to add Undo Manager before Beta 1.

**Comment by Wolfgange3311999** [comment]
What do you mean by this? Do you mean with buttons? Basic system-wide undo functionality works (ctrl+z, ctrl+shift+z).

**Comment by ryanleesipes** [comment]
I added it. Haven't marked it closed.

**Comment by ryanleesipes** [comment]
Yes I mean key shortcuts. Not physical buttons.
