### ISSUE TITLE
Draggable tabs

### ISSUE THREAD

**Issue by cybre** [evolve-os/journal#18]
1. Drag tabs around the tab bar to rearrange them.
2. Drag tabs out of the tab bar to create new windows.

**Comment by ryanleesipes** [comment]
#1 should be easy to accomplish, I will try and tackle it. #2 may take some
work, but I'll see what I can do.

**Comment by ryanleesipes** [comment]
1 has been accomplished. 2 is half accomplished.

**Comment by ryanleesipes** [comment]
Detachable tabs is moved to next release.
