### ISSUE TITLE
Icon looks weird in small sizes

### ISSUE THREAD

**Issue by cybre** [evolve-os/journal#19]
As you can see here:
![screenshot from 2015-02-16 00 05 56](https://cloud.githubusercontent.com/assets/3101505/6205492/619a2e0a-b567-11e4-9c41-1d57e0491014.png)
The icon, when displayed big, looks great.

But in the panel: 
![screenshot from 2015-02-16 00 06 12](https://cloud.githubusercontent.com/assets/3101505/6205499/c09073ba-b567-11e4-89a7-e36a5a887a38.png)
the lines are barely visible and the corners (curves) are a bit blurry.

**Comment by ryanleesipes** [comment]
Yep, fixing this right now :)
