### ISSUE TITLE
Tab bar still visible even with only one tab present

### ISSUE THREAD

**Issue by cybre** [evolve-os/journal#23]
Steps to reproduce:
1. Create new tab
2. Make some changes
3. Click on the "file changed" indicator
4. Click "OK"

As you can see, the first (and only) tab is visible when it should be hidden.

**Comment by ryanleesipes** [comment]
Is this with the newest version? Also did you post a screenshot?

**Comment by cybre** [comment]
Yes, this is the newest version (0.7.1).
Haha, I actually forgot to post the screenshot, here it is:
![screenshot from 2015-02-16 04 12 02](https://cloud.githubusercontent.com/assets/3101505/6206780/b39f1112-b589-11e4-8a9f-3ea8eae2178b.png)

**Comment by ryanleesipes** [comment]
I found the problem. Easy fix, will update here in a while. Thanks so much for your help!

**Comment by cybre** [comment]
No problem :)

**Comment by ryanleesipes** [comment]
This has been fixed! :)

**Comment by cybre** [comment]
Great!
