### ISSUE TITLE
Don't upload empty files to hastebin

### ISSUE THREAD

**Issue by cybre** [evolve-os/journal#24]
Right now, clicking the share button uploads the content to hastebin even if the document is empty, thus creating an empty paste.

**Comment by ryanleesipes** [comment]
Yes, this behavior should be changed.

**Comment by ryanleesipes** [comment]
This has been fixed in the v1.0 branch. However whitespace longer than 0 spaces is allowed to accommodate uses such as this: http://en.wikipedia.org/wiki/Whitespace_%28programming_language%29
