### ISSUE TITLE
Build issue with dynamiclist.vala

### ISSUE THREAD

**Issue by Justinzobel** [evolve-os/journal#40]
make[2]: *** No rule to make target `../src/dynamiclist.vala', needed by `journal_valac.stamp'.  Stop.
make[1]: *** [CMakeFiles/journal.dir/all] Error 2

Vala 0.26.2 on Evolve OS

**Comment by ryanleesipes** [comment]
This has been solved. /src/dynamiclist.vala was removed from CMakeLists file.

**Comment by zesterer** [comment]
Why did this become an issue? DynamicList should work fine for everything. If there's an issue, It would be great to know so I can fix it.

**Comment by ryanleesipes** [comment]
Dropped the file and moved to GLib.List after consulting with Ikey, as per
our conversation before.
