### ISSUE TITLE
[BUG] Doesn't remember theme colour after closing/re-opening

### ISSUE THREAD

**Issue by Justinzobel** [evolve-os/journal#45]
Doesn't remember theme colour after closing/re-opening

**Comment by ryanleesipes** [comment]
This all has to do with Gsettings. I may try my hand at this, although it will probably be a major chore.

**Comment by Justinzobel** [comment]
Just have a look at the way budgie does it. Should be able to steal most of
the code for it.

**Comment by ryanleesipes** [comment]
This has been done, just need to get it to remember if the window is maximized or normal - as well as the size of the window.

**Comment by ryanleesipes** [comment]
Now remembers size of window.
